# NumPy

## Creating NumPy arrays

__NumPy arrays can be created using various methods__

##  _From a list or tuple_:

In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


## _Using the arange() function to create a range of values_:

In [2]:
my_array = np.arange(1, 10)
print(my_array)

[1 2 3 4 5 6 7 8 9]


## _Using the zeros() function to create an array of zeros_:

In [3]:
my_array = np.zeros(5)
print(my_array)

[0. 0. 0. 0. 0.]


In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## _Using the ones() function to create an array of ones_:

In [5]:
my_array = np.ones(5)
print(my_array)

[1. 1. 1. 1. 1.]


In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

## _Using the linspace() function to create an array of evenly spaced values_:

In [8]:
my_array = np.linspace(0, 1, 10)
print(my_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## _Identity matrix_

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Indexing and slicing numpy arrays

In [10]:
my_array[2]

0.2222222222222222

In [11]:
my_array[0:3]

array([0.        , 0.11111111, 0.22222222])

In [12]:
my_array[-1:]

array([1.])

In [13]:
my_array[1:5:2]

array([0.11111111, 0.33333333])

# Broadcasting

In [14]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


c = a * b

print(c)

[ 4 10 18]


### complex example 1:

In [15]:
import numpy as np

# Define two arrays of different shapes
a = np.array([1+2j, 3+4j])
b = np.array([5, 6])

# Broadcasting
c = a + b[:, np.newaxis]

print(c)


[[6.+2.j 8.+4.j]
 [7.+2.j 9.+4.j]]


### complex example 2:

In [16]:

import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2, 3])

c = a * b[:, np.newaxis]

print(c)



[[ 1  2]
 [ 6  8]
 [15 18]]


### Addition

In [17]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
d = np.add(a, b)

print(c) 
print(d)


[5 7 9]
[5 7 9]


### Subtraction

In [18]:
import numpy as np

a = np.array([4, 5, 6])
b = np.array([1, 2, 3])
c = a - b
d = np.subtract(a, b)

print(c) 
print(d)


[3 3 3]
[3 3 3]


### Multiplication

In [19]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
d = np.multiply(a, b)

print(c) 
print(d) 


[ 4 10 18]
[ 4 10 18]


### Division

In [20]:
import numpy as np

a = np.array([4, 6, 8])
b = np.array([2, 3, 4])
c = a / b
d = np.divide(a, b)

print(c) 
print(d) 


[2. 2. 2.]
[2. 2. 2.]


### Exponentiation

In [21]:
import numpy as np

a = np.array([2, 3, 4])
b = np.array([3, 2, 1])
c = a ** b
d = np.power(a, b)

print(c) 
print(d) 


[8 9 4]
[8 9 4]


### Square Root

In [22]:
import numpy as np

a = np.array([4, 9, 16])
b = np.sqrt(a)

print(b)


[2. 3. 4.]


### Trigonometric Functions

In [23]:
import numpy as np

a = np.array([0, np.pi/2, np.pi])
b = np.sin(a)
c = np.cos(a)
d = np.tan(a)

print(b) 
print(c) 


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


# Vectorization

In [24]:
a = [1, 2, 3]
b = [4, 5, 6]
c = []

for i in range(len(a)):
    c.append(a[i] * b[i])

print(c)


[4, 10, 18]


In [25]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b

print(c) 

[ 4 10 18]


# numpy.random

In [26]:
import numpy as np

# generate a 3x3 array of random numbers between 0 and 1
a = np.random.rand(3, 3)

# generate a 2x2 array of random numbers from a standard normal distribution
b = np.random.randn(2, 2)

# generate a 1D array of 5 random integers between 0 and 9
c = np.random.randint(0, 10, 5)

# generate a 2x3 array of random numbers between 0 and 1
d = np.random.random_sample((2, 3))

# randomly select 3 elements from an array without replacement
e = np.random.choice([1, 2, 3, 4, 5], size=3, replace=False)

# shuffle the elements of an array in place
f = np.array([1, 2, 3, 4, 5])
np.random.shuffle(f)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


[[0.17389188 0.25523107 0.08349905]
 [0.06645089 0.04518133 0.59605967]
 [0.28235518 0.00278521 0.49640775]]
[[-0.62162698 -0.27140153]
 [-0.78134427 -1.04771505]]
[1 5 4 1 4]
[[0.07963204 0.21683464 0.84711077]
 [0.83573976 0.1738649  0.84191426]]
[5 2 3]
[2 1 5 3 4]


## Reshape

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
A = arr.reshape(5,5)

In [30]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Mathematical Functions:

In [31]:
import numpy as np

# create a 1D array
a = np.array([1, 2, 3])
x = np.array([0, 0.5, 1])

# apply basic mathematical functions to array elements
b = np.sin(a)
c = np.exp(a)
d = np.sqrt(a)

# apply trigonometric functions to array elements
e = np.arcsin(x)
f = np.tan(a)

# apply statistical functions to an array
g = np.mean(a)
h = np.max(a)
i = np.median(a)

# perform linear algebra operations
j = np.array([[1, 2], [3, 4]])
k = np.linalg.det(j)
l = np.linalg.inv(j)

print(f"b {b}\n")
print(f"c {c}\n")
print(f"d {d}\n")
print(f"e {e}\n")
print(f"f {f}\n")
print(f"g {g}\n")
print(f"h {h}\n")
print(f"i {i}\n")
print(f"j {j}\n")
print(f"k {k}\n")
print(f"l {l}\n")

b [0.84147098 0.90929743 0.14112001]

c [ 2.71828183  7.3890561  20.08553692]

d [1.         1.41421356 1.73205081]

e [0.         0.52359878 1.57079633]

f [ 1.55740772 -2.18503986 -0.14254654]

g 2.0

h 3

i 2.0

j [[1 2]
 [3 4]]

k -2.0000000000000004

l [[-2.   1. ]
 [ 1.5 -0.5]]



## To find at what index value is the max,min value located

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([31, 25, 21,  1, 16, 16,  2, 28, 17, 33])

In [34]:
ranarr.argmax()

9

In [35]:
ranarr.argmin()

3

## To find shape of a vector

In [36]:
ranarr.shape

(10,)

In [37]:
arr.shape

(25,)

In [38]:
A.shape

(5, 5)