# NumPy

## Creating NumPy arrays

__NumPy arrays can be created using various methods__

##  _From a list or tuple_:

In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


## _Using the arange() function to create a range of values_:

In [2]:
my_array = np.arange(1, 10)
print(my_array)

[1 2 3 4 5 6 7 8 9]


## _Using the zeros() function to create an array of zeros_:

In [3]:
my_array = np.zeros(5)
print(my_array)

[0. 0. 0. 0. 0.]


## _Using the ones() function to create an array of ones_:

In [4]:
my_array = np.ones(5)
print(my_array)

[1. 1. 1. 1. 1.]


## _Using the linspace() function to create an array of evenly spaced values_:

In [5]:
my_array = np.linspace(0, 1, 10)
print(my_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# Indexing and slicing numpy arrays

In [6]:
my_array[2]

0.2222222222222222

In [7]:
my_array[0:3]

array([0.        , 0.11111111, 0.22222222])

In [10]:
my_array[-1:]

array([1.])

In [11]:
my_array[1:5:2]

array([0.11111111, 0.33333333])

# Broadcasting

In [1]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


c = a * b

print(c)

[ 4 10 18]


### complex example 1:

In [2]:
import numpy as np

# Define two arrays of different shapes
a = np.array([1+2j, 3+4j])
b = np.array([5, 6])

# Broadcasting
c = a + b[:, np.newaxis]

print(c)


[[6.+2.j 8.+4.j]
 [7.+2.j 9.+4.j]]


### complex example 2:

In [10]:

import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2, 3])

c = a * b[:, np.newaxis]

print(c)



[[ 1  2]
 [ 6  8]
 [15 18]]
